### ISSUE TITLE
no augmented data generation file in repository

### ISSUE THREAD

**Issue by nelsopet** [nelsopet/lecospec#134]
We need to be able to reproduce the models used in the repo. It looks like RF mods_augmented are generated outside the repo. I looked and neither ./mle/ nor ./Scripts/ has any file generating the ./mle/.trainingAugmented.csv.

**Comment by krbundy** [comment]
The data is created in ./mle/modelDev.ipynb, though the name of the files are trainingData.csv and validation.csv

I am currently creating a file ./Scripts/augmentData.R that will handle this functionality.  I will close this once that is completed.
