### ISSUE TITLE
Reconcile divergent validation sheets

### ISSUE THREAD

**Issue by nelsopet** [nelsopet/lecospec#146]
G sheets become outdated when local versions are cleaned (eg. 2018 EightMile missing 0-30 m on raw, Ken pulled down the G sheet, hand edited the data on his machine and now is more up to date than the G sheet). Either make one stale or better yet, reconcile.

**Comment by krbundy** [comment]
The data sheets in the repository were cleaned in a PR some time ago.  I have pushed this updated data as a new sheet in the Google Sheets copy of the data as well.  

Closing the issue as resolved.
