### ISSUE TITLE
Set all empty pixels to same NoData value (255?)

### ISSUE THREAD

**Issue by nelsopet** [nelsopet/lecospec#283]
Empty tiles in full predicted output from estimate_landcover are set to "0" , which is the same as "Abiotic" while corners of tiles with predictions are set to a different NoData value. This produces blocks of grey/NoData on the edges of predicted tiles with a different color behind for the tiles with all empty pixels. Functions/dataframe_operations.R::handle_empty_tile might a logical place to fix this but care needs to be exercised in assigning any other values that are empty in the pipeline to the same NoData value.

**Comment by krbundy** [comment]
All noData values set to 2^16 -1 (i.e. 65535) to match the other NoData values

**Comment by nelsopet** [comment]
Test on Bison Gulch still produced NoData values = 0, which is the same as one of the states in the PFT maps.

**Comment by krbundy** [comment]
Appears to work on Linux 1st June 2023 (meeting)
