### ISSUE TITLE
Final grid search model runs notebook 

### ISSUE THREAD

**Issue by nelsopet** [nelsopet/lecospec#291]
Need one clean notebook per model (RF and PLS) for however many trees/components and various other grid search parameters. The final grid search settings;

1. three data sources; ground, image and ground corrected + image spectra
2. ncomps/trees: 1,2,4,8,12,16,24,32,50 and 64
3. weights (balanced weights in caret with a max 300 sample units per PFT)
4. outliers (no treatment)
5. seed (5 random seeds across orders of magnitude??)

**Comment by krbundy** [comment]
This should include the following search levels:

1.  Number of components: 1, 2, 4, 8, 12, 16, 20, 24, 32, 50, 64
2. Sources: Image, Ground, Image + corrected ground
3. Seeds: 5 seeds per run
4. Outliers and pre-processing: None
5. Balanced class weights

**Comment by krbundy** [comment]
Appears to be working - looks correct on Linux in Meeting on 1st June 2023
