### ISSUE TITLE
gs_rf_final errors with the dataset grd_raw_raw 

### ISSUE THREAD

**Issue by nelsopet** [nelsopet/lecospec#301]
Error in confusionMatrix.default(model_predictions %>% to_fg0(), test_labels %>% : The data contain levels not found in the data.
Traceback:

1. train_model(train_data, labels, test_data, test_labels, ntree = n, 
 .     max_depth = NULL, outlier_fn = outlier_functions[[o_treatment]], 
 .     preprocess_fn = preprocess_functions[[p_treatment]], weight_fn = weight_functions[[w_treatment]], 
 .     model_id = model_id, seed = seed, log_string = paste(n, filepath, 
 .         o_treatment, p_treatment, w_treatment))
2. caret::confusionMatrix(model_predictions %>% to_fg0(), test_labels %>% 
 .     as.factor() %>% to_fg0(), mode = "everything")   # at line 68-72 of file <text>
3. confusionMatrix.default(model_predictions %>% to_fg0(), test_labels %>% 
 .     as.factor() %>% to_fg0(), mode = "everything")
4. stop("The data contain levels not found in the data.")

**Comment by krbundy** [comment]
This has been fixed in PR #304 and previous:
* added the add_forb() helper function, and
* used this to add forb to the levels of the training data
