### ISSUE TITLE
Manage dependencies that are no longer maintained on CRAN

### ISSUE THREAD

**Issue by nelsopet** [nelsopet/lecospec#354]
hsdar, raster, rdgal among maybe others?

**Comment by nelsopet** [comment]
Using the renv package, we should be able to do this.

**Comment by krbundy** [comment]
Can use MRAN for older packages.  See package 'versions' for installation of specific `version` of packages.  This, I think, can be combined with `renv` to have package-specific version of packages (different from system-wide installation)

**Comment by nelsopet** [comment]
Key packages that are the source of this issue are now forked (spectrolab and hsdar) on the nelsopet Github profile
