### ISSUE TITLE
Scripts/3_Create_SpecLibPSR.R filtering spec lib breaks on PC Windows 10

### ISSUE THREAD

**Issue by nelsopet** [nelsopet/lecospec#39]
Line 107 throws the error
SpecLib%>% 
+   dplyr::filter_at(vars(-(ScanID:Area)), all_vars((.) < 1)) %>% # Removes rows with values greater than 2
+   dplyr::filter_at(vars(-(ScanID:Area)), all_vars((.) >=0)) # Removes row with values less than 0, # dim (nrows = 1984 ncol = 2157)
Error: C stack usage  15926992 is too close to the limit

**Comment by krbundy** [comment]
Issue fixed; filtering method updated.
