### ISSUE TITLE
Fix Leaflet Legend

### ISSUE THREAD

**Issue by krbundy** [nelsopet/lecospec#57]
Should adjust the Leaflet legend to include only colors/classes with at least 1% area of area.

**Comment by nelsopet** [comment]
This thread seems to indicate you can pass a string to a dummy legend of your chosing.

https://stackoverflow.com/questions/38161073/manually-adding-legend-values-in-leaflet

**Comment by nelsopet** [comment]
I think you made an update to the colors we wanted for each PFT (at least for FncGrp1) but I don't see it in the repo. We need this for plotting colors consistently for maps and barplots.
