### ISSUE TITLE
tiling step extremely slow on full data cube

### ISSUE THREAD

**Issue by nelsopet** [nelsopet/lecospec#61]
Rebuilt lecospec with new version of R (4.1.1) and on Windows 10 lecospec laptop with 24 Gb of ram. Ran install dependencies and scripts 1-4. On script 5 classifying data cube, tiling step (n=80 tiles) took more than 1 hr for 4.4 Gb file. A large tile number is needed so that each tile doesn't break memory limit in R downstream. Examine tiling outside parallelization for better optimization of tiling step to speed up workflow.

**Comment by krbundy** [comment]
Fixed in PR #70
