### ISSUE TITLE
Tiling + hsdar vs. Sprak + user defined functions

### ISSUE THREAD

**Issue by krbundy** [nelsopet/lecospec#67]
Significant bottlenecks include raster tiling and spectral library-based calculations in hsdar. For the refactor version 1.0, we have elected to keep this structure. 

Alternative would be using Spark and user-defined functions to apply the calculations in parallel.  This would also eliminate the need to calculate the entire spectral derivatives, and instead calculate the point estimates of the derivatives only where we need them.  This is something to consider in the future.

**Comment by nelsopet** [comment]
Sticking with tiling in hsdar for now.
