### ISSUE TITLE
Verify ML Model class names

### ISSUE THREAD

**Issue by krbundy** [nelsopet/lecospec#68]
Make sure that the ranger model and infrastructure is mapping the class names (strings) to integer factors (int32) in a consistent way.  We need to assure that the conversion back to strings at the end is done correctly.

**Comment by nelsopet** [comment]
Related to this is the problem of accuracy assessment. Validation of estimated presence or abundance is dependent on the states present in the training data. If the validation data has a state, such as a species of plant not found in the training data, that level of classifier (eg. species level) would have to trap this issue. An easy solution is to convert all validation states for a given taxonomic level not found in training into NA. Accuracy could not be assessed for that particular cover element. That new level would need to be added to the Species table with all the associated, progressively coarser taxonomic information. If any of the coarser taxonomic levels (eg. genus, Fnc grp 2 or 1) are present in the training dataset, that new species can be used as validation for those coarser levels.
