### ISSUE TITLE
Quadrat Order Issues in raster::extract(*)

### ISSUE THREAD

**Issue by krbundy** [nelsopet/lecospec#72]
Verify that the raster::extract() output order is matched from the input (or sort and fix it).

**Comment by krbundy** [comment]
Currently, the order of the raster::extract function appears random.

**Comment by nelsopet** [comment]
https://github.com/nelsopet/lecospec/blob/17332443bd23465c9f6629b00caad3aec6079f98/Scripts/6_Accuracy%20Assesment.R#L47
